- name: line in file
  hosts: usa
  gather_facts: no
  become: yes

  tasks:
  - name: Add line in file
    stat:
      path: /etc/ssh/sshd_config
    register: check_file
  
  - name: install new package
    yum:
      name: httpd
      state: "{{ pkg_status }}"
    when: check_file.stat.exists