---
- name: User Create
  hosts: all
  gather_facts: false
 
  vars:
    #input_file: user_list.csv
    
  tasks:
  - set_fact: 
       file_content: "{{ lookup('file', '{{ input_file }}').splitlines() }}"
  
 
  - set_fact        :
      users_list    : "{{ users_list | default([]) + [ { 'user_name': user_name, 'user_comment': user_comment } ] }}"
    vars            :
      user_name     : "{{ item.split(',')[0]  }}"
      user_comment  : "{{ item.split(',')[1]  }}"
    loop            : "{{ lookup('file', '{{ input_file }}').splitlines() }}"

  - name: Create users from {{ input_file }}
    user:
      name: "{{ item.user_name }}"
      comment: "{{ item.user_comment }}"
    loop: "{{ users_list }}"  
     